spring:
  profiles:
    active: h2-default-db,initial
  application:
    name: bluenight
  datasource:
    initialization-mode: never
    sql-script-encoding: UTF-8
    continue-on-error: true
---
spring:
  profiles: h2-in-memory-db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bluenight;DB_CLOSE_DELAY\=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
---
spring:
  profiles: initial
  datasource:
    initialization-mode: always
    continue-on-error: false
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
#          import_files: /scripts/default.sql
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
---
spring:
  profiles: h2-default-db
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2db/bluenight;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    max-active: 10
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.H2Dialect
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  h2:
    console:
      enabled: false
      path: /console
---


